# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FULLMAC_RTK_RTL8730E)	+= fullmac-8730e.o
fullmac-8730e-objs			:= rtw_drv_probe.o \
					rtw_cfg80211_ops.o \
					rtw_wiphy.o \
					rtw_regd.o \
					rtw_ethtool_ops.o \
					rtw_cfg80211_ops_ap.o \
					rtw_cfg80211_ops_key.o \
					rtw_netdev_ops.o \
					rtw_llhw_ops.o \
					rtw_llhw_event.o \
					rtw_llhw_recv.o \
					rtw_llhw_xmit.o \
					rtw_llhw_hci_ipc_msg.o \
					rtw_llhw_hci_ipc.o \

