#ifndef __RTW_LLHW_OPS_H__
#define __RTW_LLHW_OPS_H__

#include "rtw_llhw_hci_ipc.h"

#define RTW_JOIN_TIMEOUT		20000
#define DEV_REQ_NETWORK_INFO_MAX_LEN	6

enum IPC_WIFI_C2H_EVENT_TYPE {
	IPC_WIFI_API_PROCESS_DONE = 0,
	IPC_WIFI_EVT_SCAN_USER_CALLBACK,
	IPC_WIFI_EVT_SCAN_EACH_REPORT_USER_CALLBACK,
	IPC_WIFI_EVT_AUTO_RECONNECT,
	IPC_WIFI_EVT_EAP_AUTO_RECONNECT,
	IPC_WIFI_EVT_AP_CH_SWITCH,
	IPC_WIFI_EVT_HDL,
	IPC_WIFI_EVT_PROMISC_CALLBACK,
	IPC_WIFI_EVT_GET_LWIP_INFO,
	IPC_WIFI_EVT_SET_NETIF_INFO,
	IPC_WIFI_EVT_CFG80211_SCAN_REPORT
};

enum IPC_WIFI_H2C_EVENT_TYPE {
	IPC_WIFI_EVT_PROCESS_DONE = 0,
	//basic
	IPC_API_WIFI_CONNECT,
	IPC_API_WIFI_DISCONNECT,
	IPC_API_WIFI_IS_CONNECTED_TO_AP,
	IPC_API_WIFI_IS_RUNNING,
	IPC_API_WIFI_SET_CHANNEL,
	IPC_API_WIFI_GET_CHANNEL,
	IPC_API_WIFI_SET_USR_CFG,
	IPC_API_WIFI_GET_DISCONN_REASCON,
	IPC_API_WIFI_ON,
	IPC_API_WIFI_OFF,
	IPC_API_WIFI_SET_MODE,
	IPC_API_WIFI_INIT_AP,
	IPC_API_WIFI_DEINIT_AP,
	IPC_API_WIFI_START_AP,
	IPC_API_WIFI_STOP_AP,
	IPC_API_WIFI_SCAN_NETWROKS,
	IPC_API_WIFI_GET_SCANNED_AP_INFO,
	IPC_API_WIFI_SCAN_ABORT,
	//ext
	IPC_API_WIFI_PSK_INFO_SET,
	IPC_API_WIFI_PSK_INFO_GET,
	IPC_API_WIFI_GET_MAC_ADDR,
	IPC_API_WIFI_COEX_BLE_SET_SCAN_DUTY,
	IPC_API_WIFI_DRIVE_IS_MP,
	IPC_API_WIFI_GET_ASSOCIATED_CLIENT_LIST,
	IPC_API_WIFI_GET_SETTING,
	IPC_API_WIFI_SET_IPS_EN,
	IPC_API_WIFI_SET_LPS_EN,
	IPC_API_WIFI_SET_MFP_SUPPORT,
	IPC_API_WIFI_SET_GROUP_ID,
	IPC_API_WIFI_SET_PMK_CACHE_EN,
	IPC_API_WIFI_SAE_STATUS,
	IPC_API_WIFI_GET_SW_STATISTIC,
	IPC_API_WIFI_GET_PHY_STATISTIC,
	IPC_API_WIFI_SET_NETWORK_MODE,
	IPC_API_WIFI_SET_WPS_PHASE,
	IPC_API_WIFI_SET_GEN_IE,
	IPC_API_WIFI_SET_EAP_PHASE,
	IPC_API_WIFI_GET_EAP_PHASE,
	IPC_API_WIFI_SET_EAP_METHOD,
	IPC_API_WIFI_SEND_EAPOL,
	IPC_API_WIFI_CONFIG_AUTORECONNECT,
	IPC_API_WIFI_GET_AUTORECONNECT,
	IPC_API_WIFI_CUS_IE,
	IPC_API_WIFI_SET_IND_MGNT,
	IPC_API_WIFI_SEND_MGNT,
	IPC_API_WIFI_SET_TXRATE_BY_TOS,
	IPC_API_WIFI_SET_EDCA_PARAM,
	IPC_API_WIFI_SET_TX_CCA,
	IPC_API_WIFI_SET_CTS2SEFL_DUR_AND_SEND,
	IPC_API_WIFI_MAC_FILTER,
	IPC_API_WIFI_GET_ANTENNA_INFO,
	IPC_API_WIFI_GET_BAND_TYPE,
	IPC_API_WIFI_GET_AUTO_CHANNEL,
	IPC_API_WIFI_DEL_STA,
	IPC_API_WIFI_AP_CH_SWITCH,
	IPC_API_WIFI_SET_NO_BEACON_TIMEOUT,
	IPC_API_WIFI_CONFIG_CSI,
	IPC_API_WIFI_GET_CSI_REPORT,
	//inter
	IPC_API_WIFI_COEX_SET_PTA,
	IPC_API_WIFI_SET_WPA_MODE,
	IPC_API_WIFI_SET_PMF_MODE,
	IPC_API_WIFI_COEX_BT_RFK,
	IPC_API_WIFI_COEX_ZB_RFK,
	IPC_API_WIFI_SET_BT_SEL,
	IPC_API_WIFI_ADD_KEY,
	IPC_API_WIFI_GET_CHPLAN,
	//promisc
	IPC_API_PROMISC_FILTER_RETRANSMIT_PKT,
	IPC_API_PROMISC_FILTER_WITH_LEN,
	IPC_API_PROMISC_SET,
	IPC_API_PROMISC_IS_ENABLED,
	IPC_API_PROMISC_GET_FIXED_CHANNEL,
	IPC_API_PROMISC_FILTER_BY_AP_AND_PHONE_MAC,
	IPC_API_PROMISC_SET_MGNTFRAME,
	IPC_API_PROMISC_GET_CHANNEL_BY_BSSID,
	IPC_API_PROMISC_UPDATE_CANDI_AP_RSSI_AVG,
	IPC_API_PROMISC_TX_BEACON_CONTROL,
	IPC_API_PROMISC_RESUME_TX_BEACON,
	IPC_API_PROMISC_ISSUE_PROBERSP,
	IPC_API_PROMISC_INIT_PACKET_FILTER,
	IPC_API_PROMISC_ADD_PACKET_FILTER,
	IPC_API_PROMISC_PACKET_FILTER_CONTROL,
	//misc
	IPC_API_WIFI_IP_UPDATE,
	IPC_API_WIFI_IWPRIV_INFO, //dbg cmd
	IPC_API_WIFI_MP_CMD, //mp cmd
	IPC_API_WIFI_GET_NETWORK_MODE
};

enum IPC_LWIP_INFO_TYPE {
	IPC_WLAN_GET_IP,
	IPC_WLAN_GET_GW,
	IPC_WLAN_GET_GWMSK,
	IPC_WLAN_GET_HW_ADDR,
	IPC_WLAN_IS_VALID_IP
};

typedef struct inic_ipc_dev_req_msg {
	u32	enevt_id;
	u32	param_buf[DEV_MSG_PARAM_NUM];
	int	ret;
	u8	dummy[32]; /* add for 64B size alignment */
} inic_ipc_dev_req_t;

#endif /* __RTW_LLHW_OPS_H__ */
