/******************************************************************************
 *
 * Copyright(c) 2019 Realtek Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 * V008
 ******************************************************************************/

#include "../pwr.h"
#if MAC_AX_8730E_SUPPORT

struct mac_pwr_cfg mac_pwron_8730e[] = {
	{
		0x020B,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(0), BIT(0)
	},//0x42008208[24]=1
	{
		0x0940,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(6) | BIT(5), BIT(6) | BIT(5)
	},//0x42008940[6:5]=2'b11
	{
		0x0941,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(1) | BIT(0), BIT(1) | BIT(0)
	},//0x42008940[9:8]=2'b11
	{
		0x0208,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(7), BIT(7)
	},//0x42008208[7]=1
	{
		0x0218,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(5), BIT(5)
	},//0x42008218[5]=1
	{
		0x0004,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(0), BIT(0)
	},//0x40000004[0]=1
	{
		0x0020,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(0), BIT(0)
	},//0x40000020[0]=1
	{
		0x0020,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_POLL, BIT(0), 0
	},//polling 0x40000020[0]=0
	{
		0x0006,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(1) | BIT(0), BIT(1) | BIT(0)
	},//0x40000004[17:16]=2'b11
	{
		0xFFFF,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		0,
		PWR_CMD_END, 0, 0
	},
};

struct mac_pwr_cfg mac_pwroff_8730e[] = {
	{
		0x0006,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(1) | BIT(0), 0
	},//0x40000004[17:16]=2'b00
	{
		0x0020,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(1), BIT(1)
	},//0x40000020[1]=1
	{
		0x0020,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_POLL, BIT(1), 0
	},//polling 0x40000020[1]=0
	{
		0x0004,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		WIFI_REG_BASE,
		PWR_CMD_WRITE, BIT(0), 0
	},//0x40000004[0]=0
	{
		0x0218,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(5), 0
	},//0x42008218[5]=0
	{
		0x0208,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(7), 0
	},//0x42008208[7]=0
	{
		0x0940,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(6) | BIT(5), 0
	},//0x42008940[6:5]=2'b00
	{
		0x0941,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(1) | BIT(0), 0
	},//0x42008940[9:8]=2'b00
	{
		0x020B,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		SYSTEM_CTRL_BASE_LP,
		PWR_CMD_WRITE, BIT(0), 0
	},//0x42008208[24]=0
	{
		0xFFFF,
		PWR_CVALL_MSK,
		PWR_INTF_MSK_ALL,
		0,
		PWR_CMD_END, 0, 0
	},
};

/* Power on sequence */
struct mac_pwr_cfg *pwr_on_seq_8730e[] = {
	mac_pwron_8730e,
	NULL
};

/* Power off sequence */
struct mac_pwr_cfg *pwr_off_seq_8730e[] = {
	mac_pwroff_8730e,
	NULL
};
/*
#if MAC_AX_FEATURE_HV

static struct mac_pwr_cfg mac_carddisable_seq_8852a[] = {
	{0xFFFF,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 0,
	 PWR_CMD_END, 0, 0},
};

static struct mac_pwr_cfg mac_enterlps_seq_8852a[] = {
	{0x0284,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(4), 0},
	{0x0285,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(5), BIT(5)},
	{0x0286,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(6), BIT(6)},
	{0x0287,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(4), 0},
	{0x0068,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(6), 0},
	{0x8394,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(2), BIT(2)},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xC4},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x04},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x40},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xB4},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x41},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x04},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x42},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x43},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x7D},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x44},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x45},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x01},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x48},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_POLL, BIT(2), BIT(2)},
	{0x8398,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(1), BIT(1)},
	{0x8399,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x00},
	{0x839A,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x48},
	{0x839B,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x8300,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(0), BIT(0)},
	{0x8322,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(0), BIT(0)},
	{0x8322,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_POLL, BIT(1), BIT(1)},
	{0x0082,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(4), BIT(4)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(2), 0},
	{0x0082,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(5), BIT(5)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(3), 0},
	{0x0082,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(6), BIT(6)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(4), 0},
	{0x0083,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(2), BIT(2)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(5), 0},
	{0x0083,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(3), BIT(3)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(6), 0},
	{0x0083,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(4), BIT(4)},
	{0x0025,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), 0},
	{0x0090,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xB0},
	{0x0091,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xA1},
	{0x0092,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x80},
	{0x0093,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x04},
	{0x0090,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE | PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xB0},
	{0x0091,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE | PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0xA1},
	{0x0092,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE | PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x81},
	{0x0093,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE | PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, 0xFF, 0x04},
	{0x0090,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(0), BIT(0)},
	{0x0090,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_POLL, BIT(0), 0},
	{0xFFFF,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 0,
	 PWR_CMD_END, 0, 0},
};

static struct mac_pwr_cfg mac_leavelps_seq_8852a[] = {
	{0x1083,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), BIT(7)},
	{0x10C1,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), BIT(7)},
	{0x1203,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), BIT(7)},
	{0x1E5,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_POLL, BIT(7), BIT(7)},
	{0x10,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_DELAY, PWR_DELAY_MS, PWR_DELAY_MS},
	{0x8322,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(0), 0},
	{0x8322,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_POLL, BIT(1), 0},
	{0x1083,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_SDIO,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), 0},
	{0x10C1,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_PCIE,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), 0},
	{0x1203,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_USB,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(7), 0},
	{0x8304,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 PWR_BASE_MAC,
	 PWR_CMD_WRITE, BIT(0), BIT(0)},
	{0xFFFF,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 0,
	 PWR_CMD_END, 0, 0},
};

static struct mac_pwr_cfg mac_ips_seq_8852a[] = {
	{0xFFFF,
	 PWR_CVALL_MSK,
	 PWR_INTF_MSK_ALL,
	 0,
	 PWR_CMD_END, 0, 0},
};

struct mac_pwr_cfg *card_disable_seq_8852a[] = {
	mac_carddisable_seq_8852a,
	NULL
};

struct mac_pwr_cfg *enter_lps_seq_8852a[] = {
	mac_enterlps_seq_8852a,
	NULL
};

struct mac_pwr_cfg *leave_lps_seq_8852a[] = {
	mac_leavelps_seq_8852a,
	NULL
};

struct mac_pwr_cfg *ips_seq_8852a[] = {
	mac_ips_seq_8852a,
	NULL
};

#endif*/
#endif /* #if MAC_AX_8730E_SUPPORT */
