echo "CONFIG_PLATFORM_IOT:"$(CONFIG_PLATFORM_IOT)
ifeq ($(CONFIG_PLATFORM_IOT), y)
EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
EXTRA_CFLAGS += -DCONFIG_TRAFFIC_PROTECT
EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
EXTRA_CFLAGS += -DCONFIG_RADIO_WORK
EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE

EXTRA_CFLAGS += -DCONFIG_PLATFORM_IOT
EXTRA_CFLAGS += -DRTW_PHL_BCN_IOT
EXTRA_CFLAGS += -DPHL_PLATFORM_LINUX
#EXTRA_CFLAGS += -Wno-error=date-time

ifeq ($(CONFIG_AXI_HCI), y)
EXTRA_CFLAGS += -DCONFIG_PLATFORM_OPS
_PLATFORM_FILES := platform/platform_linux_axi.o
OBJS += $(_PLATFORM_FILES)
endif
endif
