dtb-$(CONFIG_ARCH_AMEBAD2) += \
	rtl8730eah-va6-generic.dtb \
	rtl8730eah-va6-full.dtb \
	rtl8730eah-va6-tests.dtb \
	rtl8730eah-va6-recovery.dtb \
	rtl8730elh-va7-generic.dtb \
	rtl8730elh-va7-full.dtb \
	rtl8730elh-va7-tests.dtb \
	rtl8730elh-va7-ranging.dtb \
	rtl8730elh-va7-recovery.dtb \
	rtl8730elh-va8-generic.dtb \
	rtl8730elh-va8-full.dtb \
	rtl8730elh-va8-tests.dtb \
	rtl8730elh-va8-recovery.dtb

subdir-y += streamunlimited
