dtb-$(CONFIG_ARCH_AMEBAD2) += \
	rtl8730elh-va7-generic.dtb \
	rtl8730elh-va7-full.dtb \
	rtl8730elh-va7-recovery.dtb \
	rtl8730elh-va8-generic.dtb \
	rtl8730elh-va8-full.dtb \
	rtl8730elh-va8-recovery.dtb

subdir-y += streamunlimited
